export const FETCH_TASK='FETCH_TASK';
export const FETCH_TASK_SUCCESS='FETCH_TASK_SUCCESS';
export const FETCH_TASK_FAIL='FETCH_TASK_FAIL';

export const FITLTER_TASK='FITLTER_TASK';
export const FITLTER_TASK_SUCCESS='FITLTER_TASK_SUCCESS';

export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_Success';
export const ADD_TASK_FAIL= 'ADD_TASK_FAIL';

export const SET_TASK_EDITING= 'SET_TASK_EDITING';

export const UPDATE_TASK= 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESS= 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAIL= 'UPDATE_TASK_FAIL';

export const DELETE_TASK= 'DELETE_TASK';
export const DELETE_TASK_SUCCESS= 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAIL= 'DELETE_TASK_FAIL';






